export const ROOMS = {
  seuil: {
    name: "Le Seuil",
    start: { col: 6, row: 9 },
    eliane: "E",
    scratches: true,
    warm: false,
    map: [
      "################",
      "L..............R",
      "L..............R",
      "L..##..........R",
      "L..##..........R",
      "L...........E..R",
      "L..............R",
      "L..##..........R",
      "L..##..........R",
      "L..............R",
      "L..............R",
      "################",
    ],
    torches: [
      { col: 1.5, row: 1.4 },
      { col: 8, row: 1.4 },
      { col: 14.2, row: 5.2 },
      { col: 14.5, row: 8.6 },
    ],
  },
  torches: {
    name: "Salle des torches",
    start: { col: 2, row: 3 },
    eliane: null,
    scratches: false,
    warm: true,
    map: [
      "############",
      "#..........#",
      "#..........#",
      "#..........#",
      "#..........#",
      "#..........#",
      "############",
    ],
    torches: [
      { col: 1.5, row: 1.4 },
      { col: 6, row: 1.4 },
      { col: 10.4, row: 1.4 },
      { col: 3, row: 4.5 },
      { col: 8.5, row: 4.5 },
    ],
  },
};
